<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_home_fas fa-shopping-cart</name>
   <tag></tag>
   <elementGuidId>df6d85ae-a1a3-4514-b836-34400ae6f446</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@href, './cart.html')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.fas.fa-shopping-cart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fced4499-397b-4c34-bca7-29f35b91e0d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>./cart.html</value>
      <webElementGuid>09f8c59e-4224-4c31-afd2-4dfc45b6ad07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-shopping-cart</value>
      <webElementGuid>d202d055-e715-47ce-b7bc-fe580c2e04d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/header[@class=&quot;header&quot;]/div[@class=&quot;header-1&quot;]/div[@class=&quot;icons&quot;]/a[@class=&quot;fas fa-shopping-cart&quot;]</value>
      <webElementGuid>96c80303-78bd-4927-9c9a-1718771ff7e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, './cart.html')]</value>
      <webElementGuid>e96687a2-fb5b-48cf-a70e-32debd944d35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>5d0de2f4-d631-4d24-a0dc-d6ccbfe4ceb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = './cart.html']</value>
      <webElementGuid>234223fc-e011-44aa-855b-53e360e52ecb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
